global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: order_service
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['order_service:9099']
